# Predicting Boston Housing Prices

## Updating a model using SageMaker

_Deep Learning Nanodegree Program | Deployment_

---

In this notebook, we will continue working with the [Boston Housing Dataset](https://www.cs.toronto.edu/~delve/data/boston/bostonDetail.html). Our goal in this notebook will be to train two different models and to use SageMaker to switch a deployed endpoint from using one model to the other. One of the benefits of using SageMaker to do this is that we can make the change without interrupting service. What this means is that we can continue sending data to the endpoint and at no point will that endpoint disappear.

## General Outline

Typically, when using a notebook instance with SageMaker, you will proceed through the following steps. Of course, not every step will need to be done with each project. Also, there is quite a lot of room for variation in many of the steps, as you will see throughout these lessons.

1. Download or otherwise retrieve the data.
2. Process / Prepare the data.
3. Upload the processed data to S3.
4. Train a chosen model.
5. Test the trained model (typically using a batch transform job).
6. Deploy the trained model.
7. Use the deployed model.

In this notebook we will be skipping step 5, testing the model. In addition, we will perform steps 4, 6 and 7 multiple times with different models.

In [59]:
# Make sure that we use SageMaker 1.x
!pip install sagemaker==1.72.0

You should consider upgrading via the '/home/ec2-user/anaconda3/envs/pytorch_p36/bin/python -m pip install --upgrade pip' command.


## Step 0: Setting up the notebook

We begin by setting up all of the necessary bits required to run our notebook. To start that means loading all of the Python modules we will need.

In [2]:
%matplotlib inline

import os

import numpy as np
import pandas as pd

from pprint import pprint
import matplotlib.pyplot as plt
from time import gmtime, strftime

from sklearn.datasets import load_boston
import sklearn.model_selection

In addition to the modules above, we need to import the various bits of SageMaker that we will be using. 

In [3]:
import sagemaker
from sagemaker import get_execution_role
from sagemaker.amazon.amazon_estimator import get_image_uri
from sagemaker.predictor import csv_serializer

# This is an object that represents the SageMaker session that we are currently operating in. This
# object contains some useful information that we will need to access later such as our region.
session = sagemaker.Session()

# This is an object that represents the IAM role that we are currently assigned. When we construct
# and launch the training job later we will need to tell it what IAM role it should have. Since our
# use case is relatively simple we will simply assign the training job the role we currently have.
role = get_execution_role()

## Step 1: Downloading the data

Fortunately, this dataset can be retrieved using sklearn and so this step is relatively straightforward.

In [13]:
boston = load_boston()
print(boston.data)
print(boston.feature_names)
print(boston.target)

[[6.3200e-03 1.8000e+01 2.3100e+00 ... 1.5300e+01 3.9690e+02 4.9800e+00]
 [2.7310e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9690e+02 9.1400e+00]
 [2.7290e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9283e+02 4.0300e+00]
 ...
 [6.0760e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 5.6400e+00]
 [1.0959e-01 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9345e+02 6.4800e+00]
 [4.7410e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 7.8800e+00]]
['CRIM' 'ZN' 'INDUS' 'CHAS' 'NOX' 'RM' 'AGE' 'DIS' 'RAD' 'TAX' 'PTRATIO'
 'B' 'LSTAT']
[24.  21.6 34.7 33.4 36.2 28.7 22.9 27.1 16.5 18.9 15.  18.9 21.7 20.4
 18.2 19.9 23.1 17.5 20.2 18.2 13.6 19.6 15.2 14.5 15.6 13.9 16.6 14.8
 18.4 21.  12.7 14.5 13.2 13.1 13.5 18.9 20.  21.  24.7 30.8 34.9 26.6
 25.3 24.7 21.2 19.3 20.  16.6 14.4 19.4 19.7 20.5 25.  23.4 18.9 35.4
 24.7 31.6 23.3 19.6 18.7 16.  22.2 25.  33.  23.5 19.4 22.  17.4 20.9
 24.2 21.7 22.8 23.4 24.1 21.4 20.  20.8 21.2 20.3 28.  23.9 24.8 22.9
 23.9 26.6 22.5 22.2 23.6 28.7 22.6 22.  22

## Step 2: Preparing and splitting the data

Given that this is clean tabular data, we don't need to do any processing. However, we do need to split the rows in the dataset up into train, test and validation sets.

In [16]:
# First we package up the input data and the target variable (the median value) as pandas dataframes. This
# will make saving the data to a file a little easier later on.

X_bos_pd = pd.DataFrame(boston.data, columns=boston.feature_names)
print(X_bos_pd)
Y_bos_pd = pd.DataFrame(boston.target)

# We split the dataset into 2/3 training and 1/3 testing sets.
X_train, X_test, Y_train, Y_test = sklearn.model_selection.train_test_split(X_bos_pd, Y_bos_pd, test_size=0.33)

# Then we split the training set further into 2/3 training and 1/3 validation sets.
X_train, X_val, Y_train, Y_val = sklearn.model_selection.train_test_split(X_train, Y_train, test_size=0.33)

        CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1    0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2    0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3    0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4    0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...    ...   
501  0.06263   0.0  11.93   0.0  0.573  6.593  69.1  2.4786  1.0  273.0   
502  0.04527   0.0  11.93   0.0  0.573  6.120  76.7  2.2875  1.0  273.0   
503  0.06076   0.0  11.93   0.0  0.573  6.976  91.0  2.1675  1.0  273.0   
504  0.10959   0.0  11.93   0.0  0.573  6.794  89.3  2.3889  1.0  273.0   
505  0.04741   0.0  11.93   0.0  0.573  6.030  80.8  2.5050  1.0  273.0   

     PTRATIO       B  LSTAT  
0       15.3  396.90   4.98  
1       17.8  396.90   9.14  
2       1

## Step 3: Uploading the training and validation files to S3

When a training job is constructed using SageMaker, a container is executed which performs the training operation. This container is given access to data that is stored in S3. This means that we need to upload the data we want to use for training to S3. We can use the SageMaker API to do this and hide some of the details.

### Save the data locally

First we need to create the train and validation csv files which we will then upload to S3.

In [17]:
# This is our local data directory. We need to make sure that it exists.
data_dir = '../data/boston'
if not os.path.exists(data_dir):
    os.makedirs(data_dir)

In [18]:
# We use pandas to save our train and validation data to csv files. Note that we make sure not to include header
# information or an index as this is required by the built in algorithms provided by Amazon. Also, it is assumed
# that the first entry in each row is the target variable.

pd.concat([Y_val, X_val], axis=1).to_csv(os.path.join(data_dir, 'validation.csv'), header=False, index=False)
pd.concat([Y_train, X_train], axis=1).to_csv(os.path.join(data_dir, 'train.csv'), header=False, index=False)

### Upload to S3

Since we are currently running inside of a SageMaker session, we can use the object which represents this session to upload our data to the 'default' S3 bucket. Note that it is good practice to provide a custom prefix (essentially an S3 folder) to make sure that you don't accidentally interfere with data uploaded from some other notebook or project.

In [20]:
print(session.default_bucket())
prefix = 'boston-update-endpoints'

val_location = session.upload_data(os.path.join(data_dir, 'validation.csv'), key_prefix=prefix)
train_location = session.upload_data(os.path.join(data_dir, 'train.csv'), key_prefix=prefix)

sagemaker-us-east-1-438691793027


## Step 4 (A): Train the XGBoost model

Now that we have the training and validation data uploaded to S3, we can construct our XGBoost model and train it. We will be making use of the high level SageMaker API to do this which will make the resulting code a little easier to read at the cost of some flexibility.

To construct an estimator, the object which we wish to train, we need to provide the location of a container which contains the training code. Since we are using a built in algorithm this container is provided by Amazon. However, the full name of the container is a bit lengthy and depends on the region that we are operating in. Fortunately, SageMaker provides a useful utility method called `get_image_uri` that constructs the image name for us.

To use the `get_image_uri` method we need to provide it with our current region, which can be obtained from the session object, and the name of the algorithm we wish to use. In this notebook we will be using XGBoost however you could try another algorithm if you wish. The list of built in algorithms can be found in the list of [Common Parameters](https://docs.aws.amazon.com/sagemaker/latest/dg/sagemaker-algo-docker-registry-paths.html).

In [21]:
# As stated above, we use this utility method to construct the image name for the training container.
xgb_container = get_image_uri(session.boto_region_name, 'xgboost')

# Now that we know which container to use, we can construct the estimator object.
xgb = sagemaker.estimator.Estimator(xgb_container, # The name of the training container
                                    role,      # The IAM role to use (our current role in this case)
                                    train_instance_count=1, # The number of instances to use for training
                                    train_instance_type='ml.m4.xlarge', # The type of instance ot use for training
                                    output_path='s3://{}/{}/output'.format(session.default_bucket(), prefix),
                                                                        # Where to save the output (the model artifacts)
                                    sagemaker_session=session) # The current SageMaker session

'get_image_uri' method will be deprecated in favor of 'ImageURIProvider' class in SageMaker Python SDK v2.
There is a more up to date SageMaker XGBoost image. To use the newer image, please set 'repo_version'='1.0-1'. For example:
	get_image_uri(region, 'xgboost', '1.0-1').
Parameter image_name will be renamed to image_uri in SageMaker Python SDK v2.


Before asking SageMaker to begin the training job, we should probably set any model specific hyperparameters. There are quite a few that can be set when using the XGBoost algorithm, below are just a few of them. If you would like to change the hyperparameters below or modify additional ones you can find additional information on the [XGBoost hyperparameter page](https://docs.aws.amazon.com/sagemaker/latest/dg/xgboost_hyperparameters.html)

In [22]:
xgb.set_hyperparameters(max_depth=5,
                        eta=0.2,
                        gamma=4,
                        min_child_weight=6,
                        subsample=0.8,
                        objective='reg:linear',
                        early_stopping_rounds=10,
                        num_round=200)

Now that we have our estimator object completely set up, it is time to train it. To do this we make sure that SageMaker knows our input data is in csv format and then execute the `fit` method.

In [23]:
# This is a wrapper around the location of our train and validation data, to make sure that SageMaker
# knows our data is in csv format.
s3_input_train = sagemaker.s3_input(s3_data=train_location, content_type='text/csv')
s3_input_validation = sagemaker.s3_input(s3_data=val_location, content_type='text/csv')

xgb.fit({'train': s3_input_train, 'validation': s3_input_validation})

's3_input' class will be renamed to 'TrainingInput' in SageMaker Python SDK v2.
's3_input' class will be renamed to 'TrainingInput' in SageMaker Python SDK v2.


2020-12-25 06:25:59 Starting - Starting the training job...
2020-12-25 06:26:01 Starting - Launching requested ML instances.........
2020-12-25 06:27:32 Starting - Preparing the instances for training...
2020-12-25 06:28:25 Downloading - Downloading input data......
2020-12-25 06:29:26 Training - Training image download completed. Training in progress..Arguments: train
[2020-12-25:06:29:27:INFO] Running standalone xgboost training.
[2020-12-25:06:29:27:INFO] File size need to be processed in the node: 0.02mb. Available memory size in the node: 8447.56mb
[2020-12-25:06:29:27:INFO] Determined delimiter of CSV input is ','
[06:29:27] S3DistributionType set as FullyReplicated
[06:29:27] 227x13 matrix with 2951 entries loaded from /opt/ml/input/data/train?format=csv&label_column=0&delimiter=,
[2020-12-25:06:29:27:INFO] Determined delimiter of CSV input is ','
[06:29:27] S3DistributionType set as FullyReplicated
[06:29:27] 112x13 matrix with 1456 entries loaded from /opt/ml/input/data/valida


2020-12-25 06:29:39 Uploading - Uploading generated training model
2020-12-25 06:29:39 Completed - Training job completed
Training seconds: 74
Billable seconds: 74


## Step 5: Test the trained model

We will be skipping this step for now.


## Step 6 (A): Deploy the trained model

Even though we used the high level approach to construct and train the XGBoost model, we will be using the lower level approach to deploy it. One of the reasons for this is so that we have additional control over how the endpoint is constructed. This will be a little more clear later on when construct more advanced endpoints.

### Build the model

Of course, before we can deploy the model, we need to first create it. The `fit` method that we used earlier created some model artifacts and we can use these to construct a model object.

In [25]:
# Remember that a model needs to have a unique name
xgb_model_name = "boston-update-xgboost-model" + strftime("%Y-%m-%d-%H-%M-%S", gmtime())

# We also need to tell SageMaker which container should be used for inference and where it should
# retrieve the model artifacts from. In our case, the xgboost container that we used for training
# can also be used for inference and the model artifacts come from the previous call to fit.
xgb_primary_container = {
    "Image": xgb_container,
    "ModelDataUrl": xgb.model_data
}

# And lastly we construct the SageMaker model
xgb_model_info = session.sagemaker_client.create_model(
                                ModelName = xgb_model_name,
                                ExecutionRoleArn = role,
                                PrimaryContainer = xgb_primary_container)

### Create the endpoint configuration

Once we have a model we can start putting together the endpoint. Recall that to do this we need to first create an endpoint configuration, essentially the blueprint that SageMaker will use to build the endpoint itself.

In [26]:
# As before, we need to give our endpoint configuration a name which should be unique
xgb_endpoint_config_name = "boston-update-xgboost-endpoint-config-" + strftime("%Y-%m-%d-%H-%M-%S", gmtime())

# And then we ask SageMaker to construct the endpoint configuration
xgb_endpoint_config_info = session.sagemaker_client.create_endpoint_config(
                            EndpointConfigName = xgb_endpoint_config_name,
                            ProductionVariants = [{
                                "InstanceType": "ml.m4.xlarge",
                                "InitialVariantWeight": 1,
                                "InitialInstanceCount": 1,
                                "ModelName": xgb_model_name,
                                "VariantName": "XGB-Model"
                            }])

### Deploy the endpoint

Now that the endpoint configuration has been created, we can ask SageMaker to build our endpoint.

**Note:** This is a friendly (repeated) reminder that you are about to deploy an endpoint. Make sure that you shut it down once you've finished with it!

In [27]:
# Again, we need a unique name for our endpoint
endpoint_name = "boston-update-endpoint-" + strftime("%Y-%m-%d-%H-%M-%S", gmtime())

# And then we can deploy our endpoint
endpoint_info = session.sagemaker_client.create_endpoint(
                    EndpointName = endpoint_name,
                    EndpointConfigName = xgb_endpoint_config_name)

In [28]:
endpoint_dec = session.wait_for_endpoint(endpoint_name)

---------------!

## Step 7 (A): Use the model

Now that our model is trained and deployed we can send some test data to it and evaluate the results.

In [29]:
response = session.sagemaker_runtime_client.invoke_endpoint(
                                                EndpointName = endpoint_name,
                                                ContentType = 'text/csv',
                                                Body = ','.join(map(str, X_test.values[0])))

In [30]:
pprint(response)

{'Body': <botocore.response.StreamingBody object at 0x7f6d53696160>,
 'ContentType': 'text/csv; charset=utf-8',
 'InvokedProductionVariant': 'XGB-Model',
 'ResponseMetadata': {'HTTPHeaders': {'content-length': '13',
                                      'content-type': 'text/csv; charset=utf-8',
                                      'date': 'Fri, 25 Dec 2020 06:39:46 GMT',
                                      'x-amzn-invoked-production-variant': 'XGB-Model',
                                      'x-amzn-requestid': '82f979ae-afd6-4b68-8ae6-49a98f07cd34'},
                      'HTTPStatusCode': 200,
                      'RequestId': '82f979ae-afd6-4b68-8ae6-49a98f07cd34',
                      'RetryAttempts': 0}}


In [31]:
result = response['Body'].read().decode("utf-8")

In [32]:
pprint(result)

'17.3714027405'


In [33]:
Y_test.values[0]

array([19.4])

## Shut down the endpoint

Now that we know that the XGBoost endpoint works, we can shut it down. We will make use of it again later.

In [34]:
session.sagemaker_client.delete_endpoint(EndpointName = endpoint_name)

{'ResponseMetadata': {'RequestId': 'bbe6f4ea-d353-4443-b87a-a71c270725b4',
  'HTTPStatusCode': 200,
  'HTTPHeaders': {'x-amzn-requestid': 'bbe6f4ea-d353-4443-b87a-a71c270725b4',
   'content-type': 'application/x-amz-json-1.1',
   'content-length': '0',
   'date': 'Fri, 25 Dec 2020 06:40:23 GMT'},
  'RetryAttempts': 0}}

## Step 4 (B): Train the Linear model

Suppose we are working in an environment where the XGBoost model that we trained earlier is becoming too costly. Perhaps the number of calls to our endpoint has increased and the length of time it takes to perform inference with the XGBoost model is becoming problematic.

A possible solution might be to train a simpler model to see if it performs nearly as well. In our case, we will construct a linear model. The process of doing this is the same as for creating the XGBoost model that we created earlier, although there are different hyperparameters that we need to set.

In [35]:
# Similar to the XGBoost model, we will use the utility method to construct the image name for the training container.
linear_container = get_image_uri(session.boto_region_name, 'linear-learner')

# Now that we know which container to use, we can construct the estimator object.
linear = sagemaker.estimator.Estimator(linear_container, # The name of the training container
                                        role,      # The IAM role to use (our current role in this case)
                                        train_instance_count=1, # The number of instances to use for training
                                        train_instance_type='ml.m4.xlarge', # The type of instance ot use for training
                                        output_path='s3://{}/{}/output'.format(session.default_bucket(), prefix),
                                                                            # Where to save the output (the model artifacts)
                                        sagemaker_session=session) # The current SageMaker session

'get_image_uri' method will be deprecated in favor of 'ImageURIProvider' class in SageMaker Python SDK v2.
Parameter image_name will be renamed to image_uri in SageMaker Python SDK v2.


Before asking SageMaker to train our model, we need to set some hyperparameters. In this case we will be using a linear model so the number of hyperparameters we need to set is much fewer. For more details see the [Linear model hyperparameter page](https://docs.aws.amazon.com/sagemaker/latest/dg/ll_hyperparameters.html)

In [36]:
linear.set_hyperparameters(feature_dim=13, # Our data has 13 feature columns
                           predictor_type='regressor', # We wish to create a regression model
                           mini_batch_size=200) # Here we set how many samples to look at in each iteration

Now that the hyperparameters have been set, we can ask SageMaker to fit the linear model to our data.

In [37]:
linear.fit({'train': s3_input_train, 'validation': s3_input_validation})

2020-12-25 06:40:53 Starting - Starting the training job...
2020-12-25 06:40:56 Starting - Launching requested ML instances......
2020-12-25 06:42:10 Starting - Preparing the instances for training......
2020-12-25 06:43:18 Downloading - Downloading input data......
2020-12-25 06:44:04 Training - Downloading the training image..Docker entrypoint called with argument(s): train
Running default environment configuration script
[12/25/2020 06:44:29 INFO 139763891361600] Reading default configuration from /opt/amazon/lib/python2.7/site-packages/algorithm/resources/default-input.json: {u'loss_insensitivity': u'0.01', u'epochs': u'15', u'feature_dim': u'auto', u'init_bias': u'0.0', u'lr_scheduler_factor': u'auto', u'num_calibration_samples': u'10000000', u'accuracy_top_k': u'3', u'_num_kv_servers': u'auto', u'use_bias': u'true', u'num_point_for_scaler': u'10000', u'_log_level': u'info', u'quantile': u'0.5', u'bias_lr_mult': u'auto', u'lr_scheduler_step': u'auto', u'init_method': u'uniform', u


2020-12-25 06:44:44 Uploading - Uploading generated training model
2020-12-25 06:44:44 Completed - Training job completed
Training seconds: 86
Billable seconds: 86


## Step 6 (B): Deploy the trained model

Similar to the XGBoost model, now that we've fit the model we need to deploy it. Also like the XGBoost model, we will use the lower level approach so that we have more control over the endpoint that gets created.

### Build the model

Of course, before we can deploy the model, we need to first create it. The `fit` method that we used earlier created some model artifacts and we can use these to construct a model object.

In [38]:
# First, we create a unique model name
linear_model_name = "boston-update-linear-model" + strftime("%Y-%m-%d-%H-%M-%S", gmtime())

# We also need to tell SageMaker which container should be used for inference and where it should
# retrieve the model artifacts from. In our case, the linear-learner container that we used for training
# can also be used for inference.
linear_primary_container = {
    "Image": linear_container,
    "ModelDataUrl": linear.model_data
}

# And lastly we construct the SageMaker model
linear_model_info = session.sagemaker_client.create_model(
                                ModelName = linear_model_name,
                                ExecutionRoleArn = role,
                                PrimaryContainer = linear_primary_container)

### Create the endpoint configuration

Once we have the model we can start putting together the endpoint by creating an endpoint configuration.

In [39]:
# As before, we need to give our endpoint configuration a name which should be unique
linear_endpoint_config_name = "boston-linear-endpoint-config-" + strftime("%Y-%m-%d-%H-%M-%S", gmtime())

# And then we ask SageMaker to construct the endpoint configuration
linear_endpoint_config_info = session.sagemaker_client.create_endpoint_config(
                            EndpointConfigName = linear_endpoint_config_name,
                            ProductionVariants = [{
                                "InstanceType": "ml.m4.xlarge",
                                "InitialVariantWeight": 1,
                                "InitialInstanceCount": 1,
                                "ModelName": linear_model_name,
                                "VariantName": "Linear-Model"
                            }])

### Deploy the endpoint

Now that the endpoint configuration has been created, we can ask SageMaker to build our endpoint.

**Note:** This is a friendly (repeated) reminder that you are about to deploy an endpoint. Make sure that you shut it down once you've finished with it!

In [40]:
# Again, we need a unique name for our endpoint
endpoint_name = "boston-update-endpoint-" + strftime("%Y-%m-%d-%H-%M-%S", gmtime())

# And then we can deploy our endpoint
endpoint_info = session.sagemaker_client.create_endpoint(
                    EndpointName = endpoint_name,
                    EndpointConfigName = linear_endpoint_config_name)

In [41]:
endpoint_dec = session.wait_for_endpoint(endpoint_name)

-------------!

## Step 7 (B): Use the model

Just like with the XGBoost model, we will send some data to our endpoint to make sure that it is working properly. An important note is that the output format for the linear model is different from the XGBoost model.

In [42]:
response = session.sagemaker_runtime_client.invoke_endpoint(
                                                EndpointName = endpoint_name,
                                                ContentType = 'text/csv',
                                                Body = ','.join(map(str, X_test.values[0])))

In [43]:
pprint(response)

{'Body': <botocore.response.StreamingBody object at 0x7f6d53688240>,
 'ContentType': 'application/json',
 'InvokedProductionVariant': 'Linear-Model',
 'ResponseMetadata': {'HTTPHeaders': {'content-length': '48',
                                      'content-type': 'application/json',
                                      'date': 'Fri, 25 Dec 2020 06:54:23 GMT',
                                      'x-amzn-invoked-production-variant': 'Linear-Model',
                                      'x-amzn-requestid': '2f44cd6d-00ec-4dcf-a22d-9f06b188c418'},
                      'HTTPStatusCode': 200,
                      'RequestId': '2f44cd6d-00ec-4dcf-a22d-9f06b188c418',
                      'RetryAttempts': 0}}


In [44]:
result = response['Body'].read().decode("utf-8")

In [45]:
pprint(result)

'{"predictions": [{"score": 23.876432418823242}]}'


In [46]:
Y_test.values[0]

array([19.4])

## Shut down the endpoint

Now that we know that the Linear model's endpoint works, we can shut it down.

In [47]:
session.sagemaker_client.delete_endpoint(EndpointName = endpoint_name)

{'ResponseMetadata': {'RequestId': 'a6177670-5e5b-4121-a14a-6bf98d0fefe3',
  'HTTPStatusCode': 200,
  'HTTPHeaders': {'x-amzn-requestid': 'a6177670-5e5b-4121-a14a-6bf98d0fefe3',
   'content-type': 'application/x-amz-json-1.1',
   'content-length': '0',
   'date': 'Fri, 25 Dec 2020 06:54:33 GMT'},
  'RetryAttempts': 0}}

## Step 6 (C): Deploy a combined model

So far we've constructed two separate models which we could deploy and use. Before we talk about how we can change a deployed endpoint from one configuration to another, let's consider a slightly different situation. Suppose that before we switch from using only the XGBoost model to only the Linear model, we first want to do something like an A-B test, where we send some of the incoming data to the XGBoost model and some of the data to the Linear model.

Fortunately, SageMaker provides this functionality. And to actually get SageMaker to do this for us is not too different from deploying a model in the way that we've already done. The only difference is that we need to list more than one model in the production variants parameter of the endpoint configuration.

A reasonable question to ask is, how much data is sent to each of the models that I list in the production variants parameter? The answer is that it depends on the weight set for each model.

Suppose that we have $k$ models listed in the production variants and that each model $i$ is assigned the weight $w_i$. Then each model $i$ will receive $w_i / W$ of the traffic where $W = \sum_{i} w_i$.

In our case, since we have two models, the linear model and the XGBoost model, and each model has weight 1, we see that each model will get 1 / (1 + 1) = 1/2 of the data sent to the endpoint.

In [48]:
# As before, we need to give our endpoint configuration a name which should be unique
combined_endpoint_config_name = "boston-combined-endpoint-config-" + strftime("%Y-%m-%d-%H-%M-%S", gmtime())

# And then we ask SageMaker to construct the endpoint configuration
combined_endpoint_config_info = session.sagemaker_client.create_endpoint_config(
                            EndpointConfigName = combined_endpoint_config_name,
                            ProductionVariants = [
                                { # First we include the linear model
                                    "InstanceType": "ml.m4.xlarge",
                                    "InitialVariantWeight": 1,
                                    "InitialInstanceCount": 1,
                                    "ModelName": linear_model_name,
                                    "VariantName": "Linear-Model"
                                }, { # And next we include the xgb model
                                    "InstanceType": "ml.m4.xlarge",
                                    "InitialVariantWeight": 1,
                                    "InitialInstanceCount": 1,
                                    "ModelName": xgb_model_name,
                                    "VariantName": "XGB-Model"
                                }])

Now that we've created the endpoint configuration, we can ask SageMaker to construct the endpoint.

**Note:** This is a friendly (repeated) reminder that you are about to deploy an endpoint. Make sure that you shut it down once you've finished with it!

In [49]:
# Again, we need a unique name for our endpoint
endpoint_name = "boston-update-endpoint-" + strftime("%Y-%m-%d-%H-%M-%S", gmtime())

# And then we can deploy our endpoint
endpoint_info = session.sagemaker_client.create_endpoint(
                    EndpointName = endpoint_name,
                    EndpointConfigName = combined_endpoint_config_name)

In [50]:
endpoint_dec = session.wait_for_endpoint(endpoint_name)

-----------------!

## Step 7 (C): Use the model

Now that we've constructed an endpoint which sends data to both the XGBoost model and the linear model we can send some data to the endpoint and see what sort of results we get back.

In [51]:
response = session.sagemaker_runtime_client.invoke_endpoint(
                                                EndpointName = endpoint_name,
                                                ContentType = 'text/csv',
                                                Body = ','.join(map(str, X_test.values[0])))
pprint(response)

{'Body': <botocore.response.StreamingBody object at 0x7f6d530c04e0>,
 'ContentType': 'text/csv; charset=utf-8',
 'InvokedProductionVariant': 'XGB-Model',
 'ResponseMetadata': {'HTTPHeaders': {'content-length': '13',
                                      'content-type': 'text/csv; charset=utf-8',
                                      'date': 'Fri, 25 Dec 2020 07:03:49 GMT',
                                      'x-amzn-invoked-production-variant': 'XGB-Model',
                                      'x-amzn-requestid': '98dac9a0-fb87-492a-a4cf-bc0ce82b1e45'},
                      'HTTPStatusCode': 200,
                      'RequestId': '98dac9a0-fb87-492a-a4cf-bc0ce82b1e45',
                      'RetryAttempts': 0}}


Since looking at a single response doesn't give us a clear look at what is happening, we can instead take a look at a few different responses to our endpoint

In [52]:
for rec in range(10):
    response = session.sagemaker_runtime_client.invoke_endpoint(
                                                EndpointName = endpoint_name,
                                                ContentType = 'text/csv',
                                                Body = ','.join(map(str, X_test.values[rec])))
    pprint(response)
    result = response['Body'].read().decode("utf-8")
    print(result)
    print(Y_test.values[rec])

{'Body': <botocore.response.StreamingBody object at 0x7f6d530db438>,
 'ContentType': 'text/csv; charset=utf-8',
 'InvokedProductionVariant': 'XGB-Model',
 'ResponseMetadata': {'HTTPHeaders': {'content-length': '13',
                                      'content-type': 'text/csv; charset=utf-8',
                                      'date': 'Fri, 25 Dec 2020 07:03:55 GMT',
                                      'x-amzn-invoked-production-variant': 'XGB-Model',
                                      'x-amzn-requestid': 'b0e3bd1b-b367-4b7c-9a09-5d95f58bb571'},
                      'HTTPStatusCode': 200,
                      'RequestId': 'b0e3bd1b-b367-4b7c-9a09-5d95f58bb571',
                      'RetryAttempts': 0}}
17.3714027405
[19.4]
{'Body': <botocore.response.StreamingBody object at 0x7f6d530db1d0>,
 'ContentType': 'text/csv; charset=utf-8',
 'InvokedProductionVariant': 'XGB-Model',
 'ResponseMetadata': {'HTTPHeaders': {'content-length': '13',
                                     

If at some point we aren't sure about the properties of a deployed endpoint, we can use the `describe_endpoint` function to get SageMaker to return a description of the deployed endpoint.

In [53]:
pprint(session.sagemaker_client.describe_endpoint(EndpointName=endpoint_name))

{'CreationTime': datetime.datetime(2020, 12, 25, 6, 54, 49, 759000, tzinfo=tzlocal()),
 'EndpointArn': 'arn:aws:sagemaker:us-east-1:438691793027:endpoint/boston-update-endpoint-2020-12-25-06-54-49',
 'EndpointConfigName': 'boston-combined-endpoint-config-2020-12-25-06-54-42',
 'EndpointName': 'boston-update-endpoint-2020-12-25-06-54-49',
 'EndpointStatus': 'InService',
 'LastModifiedTime': datetime.datetime(2020, 12, 25, 7, 3, 14, 161000, tzinfo=tzlocal()),
 'ProductionVariants': [{'CurrentInstanceCount': 1,
                         'CurrentWeight': 1.0,
                         'DeployedImages': [{'ResolutionTime': datetime.datetime(2020, 12, 25, 6, 54, 54, 388000, tzinfo=tzlocal()),
                                             'ResolvedImage': '382416733822.dkr.ecr.us-east-1.amazonaws.com/linear-learner@sha256:41e60ef0039366d7c1332b728e44d43b2693177d079b5bde332b3dfd298d9c30',
                                             'SpecifiedImage': '382416733822.dkr.ecr.us-east-1.amazonaws.com/

## Updating an Endpoint

Now suppose that we've done our A-B test and the new linear model is working well enough. What we'd like to do now is to switch our endpoint from sending data to both the XGBoost model and the linear model to sending data only to the linear model.

Of course, we don't really want to shut down the endpoint to do this as doing so would interrupt service to whoever depends on our endpoint. Instead, we can ask SageMaker to **update** an endpoint to a new endpoint configuration.

What is actually happening is that SageMaker will set up a new endpoint with the new characteristics. Once this new endpoint is running, SageMaker will switch the old endpoint so that it now points at the newly deployed model, making sure that this happens seamlessly in the background.

In [54]:
session.sagemaker_client.update_endpoint(EndpointName=endpoint_name, EndpointConfigName=linear_endpoint_config_name)

{'EndpointArn': 'arn:aws:sagemaker:us-east-1:438691793027:endpoint/boston-update-endpoint-2020-12-25-06-54-49',
 'ResponseMetadata': {'RequestId': '8f273b37-63df-436c-a959-72b6a9fcbedf',
  'HTTPStatusCode': 200,
  'HTTPHeaders': {'x-amzn-requestid': '8f273b37-63df-436c-a959-72b6a9fcbedf',
   'content-type': 'application/x-amz-json-1.1',
   'content-length': '110',
   'date': 'Fri, 25 Dec 2020 07:04:15 GMT'},
  'RetryAttempts': 0}}

To get a glimpse at what is going on, we can ask SageMaker to describe our in-use endpoint now, before the update process has completed. When we do so, we can see that the in-use endpoint still has the same characteristics it had before.

In [55]:
pprint(session.sagemaker_client.describe_endpoint(EndpointName=endpoint_name))

{'CreationTime': datetime.datetime(2020, 12, 25, 6, 54, 49, 759000, tzinfo=tzlocal()),
 'EndpointArn': 'arn:aws:sagemaker:us-east-1:438691793027:endpoint/boston-update-endpoint-2020-12-25-06-54-49',
 'EndpointConfigName': 'boston-combined-endpoint-config-2020-12-25-06-54-42',
 'EndpointName': 'boston-update-endpoint-2020-12-25-06-54-49',
 'EndpointStatus': 'Updating',
 'LastModifiedTime': datetime.datetime(2020, 12, 25, 7, 4, 16, 172000, tzinfo=tzlocal()),
 'ProductionVariants': [{'CurrentInstanceCount': 1,
                         'CurrentWeight': 1.0,
                         'DeployedImages': [{'ResolutionTime': datetime.datetime(2020, 12, 25, 6, 54, 54, 388000, tzinfo=tzlocal()),
                                             'ResolvedImage': '382416733822.dkr.ecr.us-east-1.amazonaws.com/linear-learner@sha256:41e60ef0039366d7c1332b728e44d43b2693177d079b5bde332b3dfd298d9c30',
                                             'SpecifiedImage': '382416733822.dkr.ecr.us-east-1.amazonaws.com/l

If we now wait for the update process to complete, and then ask SageMaker to describe the endpoint, it will return the characteristics of the new endpoint configuration.

In [56]:
endpoint_dec = session.wait_for_endpoint(endpoint_name)

-----------------!

In [57]:
pprint(session.sagemaker_client.describe_endpoint(EndpointName=endpoint_name))

{'CreationTime': datetime.datetime(2020, 12, 25, 6, 54, 49, 759000, tzinfo=tzlocal()),
 'EndpointArn': 'arn:aws:sagemaker:us-east-1:438691793027:endpoint/boston-update-endpoint-2020-12-25-06-54-49',
 'EndpointConfigName': 'boston-linear-endpoint-config-2020-12-25-06-45-16',
 'EndpointName': 'boston-update-endpoint-2020-12-25-06-54-49',
 'EndpointStatus': 'InService',
 'LastModifiedTime': datetime.datetime(2020, 12, 25, 7, 12, 34, 899000, tzinfo=tzlocal()),
 'ProductionVariants': [{'CurrentInstanceCount': 1,
                         'CurrentWeight': 1.0,
                         'DeployedImages': [{'ResolutionTime': datetime.datetime(2020, 12, 25, 7, 4, 18, 646000, tzinfo=tzlocal()),
                                             'ResolvedImage': '382416733822.dkr.ecr.us-east-1.amazonaws.com/linear-learner@sha256:41e60ef0039366d7c1332b728e44d43b2693177d079b5bde332b3dfd298d9c30',
                                             'SpecifiedImage': '382416733822.dkr.ecr.us-east-1.amazonaws.com/li

## Shut down the endpoint

Now that we've finished, we need to make sure to shut down the endpoint.

In [58]:
session.sagemaker_client.delete_endpoint(EndpointName = endpoint_name)

{'ResponseMetadata': {'RequestId': '271aa2aa-42e7-416f-b677-9f06fd81ee0e',
  'HTTPStatusCode': 200,
  'HTTPHeaders': {'x-amzn-requestid': '271aa2aa-42e7-416f-b677-9f06fd81ee0e',
   'content-type': 'application/x-amz-json-1.1',
   'content-length': '0',
   'date': 'Fri, 25 Dec 2020 07:13:01 GMT'},
  'RetryAttempts': 0}}

## Optional: Clean up

The default notebook instance on SageMaker doesn't have a lot of excess disk space available. As you continue to complete and execute notebooks you will eventually fill up this disk space, leading to errors which can be difficult to diagnose. Once you are completely finished using a notebook it is a good idea to remove the files that you created along the way. Of course, you can do this from the terminal or from the notebook hub if you would like. The cell below contains some commands to clean up the created files from within the notebook.

In [ ]:
# First we will remove all of the files contained in the data_dir directory
!rm $data_dir/*

# And then we delete the directory itself
!rmdir $data_dir